### ISSUE TITLE
4-wide desktop ability

### ISSUE THREAD

**Issue by serakfalcon** [GavickPro/Grid-GK5#10]
Is it possible to have 4 same-size blocks across for the desktop? My site needs an amount divisble by 4, however 6 blocks wide does not allow that. Is there anything I can do about that?

**Comment by dziudek** [comment]
Hello,

The only and hacky way can be setting the desktop width to 5000px and tablet width to 4999px - then the module will load the tablet view (with 4-columns grid) on the desktop and tablet devices.

**Comment by serakfalcon** [comment]
In the end everywhere in the code where there was 6 I doubled it and it seems to work, though it affected the heights of elements for some reason.

**Comment by dziudek** [comment]
So my tip wasn't working for you?

**Comment by serakfalcon** [comment]
i'm sure it'd work but it seemed to make more sense to make the desktop units out of 12 instead of 6, which allows for division by 4, rather than messing with the desktop and tablet widths.
