### ISSUE TITLE
All grids disappear afte update to Grid 1.2

### ISSUE THREAD

**Issue by alkemiko** [GavickPro/Grid-GK5#15]
Hello,I've trying to update module in this site, in locahost it work but in remote site 
http://www.alangelbags.com/it/collezione/collezione-primavera-estate-2014/linea-fashion.html all gris into site disappear after updating to Grid-GK5 v 1.2

Alex

**Comment by alkemiko** [comment]
Now i've reinstalled V1.1 beacause . Joomla! 3.2.3 Stable version.

**Comment by alkemiko** [comment]
Now i've reinstalled V1.1   Joomla! 3.2.3 Stable version.

**Comment by alkemiko** [comment]
Sorry, problem is also in localhost site

**Comment by bkrztuk** [comment]
Could you provide me access to your installation? When you create new module you can save configuraion properly?

**Comment by bkrztuk** [comment]
I've installed latest package of (M) Social template, check Grid config and then update Grid module to version v1.2 and all is working fine, screencast you can watch here >> http://recordit.co/wKb6LmTvoZ

So probably this is something with your installation, please try to uninstall module and use latest v.1.2 version.

**Comment by alkemiko** [comment]
Hello,
than'ks for reply. The problem is not in the administrator page (all modules in admin page works corretcly) but it's on front-end page. Problem is in fantasy module name to load modules in article page). All modules loaded in articles page disappearing. If rename the "fantasy module name" the module loaded in article page appears again, but I've multpiles modules loaded in multiple articles pages...

**Comment by alkemiko** [comment]
"fantasy module name is the modules name not present in module template position but is a fantasy name to load module in article page

**Comment by alkemiko** [comment]
ok better (sorry for my english) ... fantasy position name module (its correct name)

**Comment by bkrztuk** [comment]
On article page you mean some regular module position or just module loaded by some 3rd party extension like Modules anywhere or loadposition code?

**Comment by alkemiko** [comment]
![screenshot 1](https://cloud.githubusercontent.com/assets/2822163/2693126/601b09a0-c3af-11e3-88c9-5e7d2dd620d6.jpg)
![screenshot 2](https://cloud.githubusercontent.com/assets/2822163/2693127/601d4184-c3af-11e3-809e-c8c8b4620d40.jpg)

**Comment by alkemiko** [comment]
Problem is with {loadposition code}

**Comment by bkrztuk** [comment]
If the module works in standalone mode it is not Grid issue, could you check module on some regular module position?

**Comment by alkemiko** [comment]
Hello, 

tk's for reply. Okay assign module to a some regular position it work only it have a notice: Notice: Constant DS already defined in C:\UniServerZ\www\gk_meet\modules\mod_grid_gk5\mod_grid_gk5.php on line 15
I've discevered that if I assign the Grid Module to same "fantasy" name module position and then save the module it work ...

**Comment by bkrztuk** [comment]
So it is probably problem with this loadposition code, module after update is working fine with regular positions.

**Comment by giupi** [comment]
Hello,

(Joomla 2.5.19)

I've also had the same problem: after upgrading to 1.2 all the grids disappeared (in firefox) or they appeared completely messed up (in chrome); so I got back to 1.1 (perfectly working).

The problem arised both upgrading via Extension Manager: Update, or via Extension Manager: Install uploading 1.2 version file.

I have no loadposition code; my grid shows only gk4 images each having a position (not included in the template).

Thanks for your support...

**Comment by dziudek** [comment]
All grids disappear on the frontpage or in the back-end? If in the frontpage then most probably it is connected with the new feature of the proportions for the grid elements - the values are not existing in the module settings so it returns 0 and makes grid elements invisble. You should set the grid proportions options to 1, resave it and then all grid elements should appear correctly.

**Comment by giupi** [comment]
Hello, thanks for your answer... yes the grid disappeared in frontpage, but when I opened Gk5Grid module setting the proportion was already 1 by default (even if I did not understand what this setting is for) in desktop, tablet and phone.

I did not think to resave again because... maybe this could solve?

**Comment by bkrztuk** [comment]
You just see the default value and you need to save module configuration to store this data in database.

**Comment by giupi** [comment]
Ok ok... saving the Gk5Grid module settings (even without changing them) after the update solved the problem... thanks!
