### ISSUE TITLE
Position not showing for 30+ blocks

### ISSUE THREAD

**Issue by hyunster** [GavickPro/Grid-GK5#17]
Hello, 

I have 50 blocks that I created in the grid. However, I cannot assign/and do not see beyond position 30 on the drop-down Position list in my Custom HTML Module. How can I access blocks 31-50?

Thanks!

![screen shot 2014-08-05 at 10 32 12 pm](https://cloud.githubusercontent.com/assets/2236177/3821621/e5009e08-1d11-11e4-92a3-22360c299bd7.png)

![screen shot 2014-08-05 at 10 30 58 pm](https://cloud.githubusercontent.com/assets/2236177/3821607/bda8b0ac-1d11-11e4-9c63-949db240c94c.png)

**Comment by hyunster** [comment]
Found it. Thanks.
http://www.gavick.com/documentation/joomla-templates/customizing-joomla-template/how-to-add-new-module-position/

**Comment by dziudek** [comment]
Hello,

Please also remember that you can use only one module position - using as a module position name grid1[1], grid1[2] etc.
