### ISSUE TITLE
how to add link and picture on a grid

### ISSUE THREAD

**Issue by saamy91** [GavickPro/Grid-GK5#20]
Hello,

I'm using the free module, Metro GRID, can you explain me how to add an link and a picture to an GRID position ? I try to search an documentation to find a turorial but i can't find.
I wanna add a custom image and picture in a grid position like in your demo version: https://demo.gavick.com/joomla25/msocial/

Link of module:
https://www.gavick.com/metro-grid-joomla-module

Advance thnks.
Regards,

**Comment by dziudek** [comment]
Hello,

Configuration for every module in the MSocial template is available here: https://www.gavick.com/documentation/joomla-templates/joomla-templates-configuration/msocial-configuration

**Comment by edbitd** [comment]
Just so you know.. that does not answer the question. The issue is not how to configure it, the issue is how to load the actual content. How to add a profile link as in the demo.

**Comment by dziudek** [comment]
So please look how we have set up modules on the specific module positions like grid1.
