### ISSUE TITLE
Grids overlaping

### ISSUE THREAD

**Issue by jviassolo** [GavickPro/Grid-GK5#25]
Hi, i´m working with this module but i cant solve this problem, my grid is overlaping. Thanks-
![overlapping](https://cloud.githubusercontent.com/assets/21360217/18126509/d0e67458-6f51-11e6-88b3-4d1f16239f4b.jpg)

**Comment by dziudek** [comment]
Hi, unfortunately without URL to your website I am unable to help you.

**Comment by jviassolo** [comment]
Sorry this is the url www.aduananews.com, Thanks.

2016-09-01 5:35 GMT-03:00 Tomasz Dziuda notifications@github.com:

**Comment by dziudek** [comment]
Please try to apply this fix: https://github.com/GavickPro/Grid-GK5/commit/b38bb97a575b0723b3c5732c94710d73d4494e4b

**Comment by jviassolo** [comment]
Gracias por tu respuesta amigo, No entiendo, donde debo aplicar esta
revisión ??

2016-09-02 11:51 GMT-03:00 Tomasz Dziuda notifications@github.com:

**Comment by dziudek** [comment]
Please response in english.

**Comment by jviassolo** [comment]
Thanks for rply, where i need to aplly this code ? b38bb97
https://github.com/GavickPro/Grid-GK5/commit/b38bb97a575b0723b3c5732c94710d73d4494e4b

2016-09-05 4:35 GMT-03:00 Tomasz Dziuda notifications@github.com:

**Comment by dziudek** [comment]
In the modules/mod_grid_gk5/helper.php file

**Comment by jviassolo** [comment]
Great work, now is all good, take a look. Thanks for your time.

www.aduananews.com

2016-09-06 2:41 GMT-03:00 Tomasz Dziuda notifications@github.com:
