### ISSUE TITLE
Loop loading issue joomla 3.x 

### ISSUE THREAD

**Issue by madaura** [GavickPro/Grid-GK5#3]
Hi,
I just installed the module, set it in the home menu with 3 grid positions, created the 3 modules with some fake images to see how it looks in the template.
For any reason, the images are not showed, instead appears the little icon showed when an image is not found. So I just replace the images with some text in each module position and although the text is showed, the loading icon in the center never stop, like if there is something missing.

Please see the attached image to get a better understanding what I meaning, 
Thanks for your help,
Best, 
Dario P.

![grid](https://f.cloud.github.com/assets/6420642/1931560/3da5a0ac-7ec1-11e3-8b77-812db7a24256.png)

**Comment by dziudek** [comment]
Hello,

Please provide an URL to your website - without it we will be unable to help you.

**Comment by madaura** [comment]
Hello,

Sorry for the delay,

The module is working right know (http://suviviendainternacional.com/test/jupgrade1/es/) however I have one question:

I have noted in the middle of the module that the processing icon never stop, it doesn't matter?

Thanks for your reply! 

Best,

Dario Patino
System Engineer
Madaura.com - Founder

**Comment by dziudek** [comment]
I'll add in the next version feature to hide the loader when module is loaded. It needs adding additional CSS class when module finishes loading.

**Comment by iuzer** [comment]
Loop loading issue is also in joomla 2.5.19 version

**Comment by dziudek** [comment]
@iuzer - please just download the latest version from this repository - this problem was fixed here: https://github.com/GavickPro/Grid-GK5/commit/aab838d6675f842b7b27ddf37d37b8f6793cdc46

**Comment by OIDInfoDesign** [comment]
GavickPro4 - images not loading
I am having a problem with the slideshow not loading images - the loading indicator just spins and spins. It has bee working fine until a few days ago. Can you provide any direction on how to fix this? Here is the website with the issue.
http://www.townofindianhead.com/
