### ISSUE TITLE
Vertical lines between elements.

### ISSUE THREAD

**Issue by Cyberek** [GavickPro/Grid-GK5#5]
More and more users complain about vertical lines that show between elements when parent width cant be divided by 2 or 4. In that case background can be seen in 1px space between elements.

(https://www.gavick.com/forums/m-social/white-vertical-line-on-gk-grid-in-msocial-32971.html?p=162039#p162039)

**Comment by dziudek** [comment]
It seems that I've found a solution: https://github.com/GavickPro/Grid-GK5/commit/26e208edc4884c4be9479224686ebae528491fc9
