### ISSUE TITLE
My Site Disappears Whenever Module is Published

### ISSUE THREAD

**Issue by MarenLBC** [GavickPro/Grid-GK5#6]
Hello,

Whenever I publish the module, my entire site disappears and the only thing that is left are the grid blocks listed vertically in one column. My error console is not returning anything either. Thank you so much for any assistance you could provide. Site is: www.dscauctions.com. I've unpublished the module so you will not be able to see the error live. I however will reactivate upon request.

Keep up the good work!

**Comment by dziudek** [comment]
Hello,

The problem was solved? Because as I see now the Grid is displayed correctly on your website.
