### ISSUE TITLE
White Space - How to delete it??

### ISSUE THREAD

**Issue by Accesoalanube** [GavickPro/Grid-GK5#7]
Hi friends!

I recently installed this very great module and seems to work so fine, but I have a horrible white space between the grid elements, so could you please take a look and tell me what to do??

I saw that the issue is related to screen size, some images attached (netbook, mobile and tablet views included) 

Netbook view 1024 x 768px - Zoom 100% - Chrome Browser 
![white-space-removal](https://f.cloud.github.com/assets/6855029/2340855/e20754ee-a4cb-11e3-9435-7d8319918fa8.jpg)

Netbook view 1024 x 768px - Zoom 75% - Chrome Browser 
![netbook-grid-75-percent-view](https://f.cloud.github.com/assets/6855029/2341470/30d82890-a4dc-11e3-9bf2-aff8133c4b6c.jpg)

Tablet 7" Vertical View
![screenshot_2014-03-05-13-04-44](https://f.cloud.github.com/assets/6855029/2341327/815058a6-a4d7-11e3-89d2-bb634a13ced4.png)

Tablet 7" Horizontal View
![screenshot_2014-03-05-20-39-25](https://f.cloud.github.com/assets/6855029/2341363/ba57ea14-a4d8-11e3-97b3-e5ed73760ac7.png)

Mobile Vertical View
![sc20140305-161303](https://f.cloud.github.com/assets/6855029/2341443/2284dd2a-a4db-11e3-968d-c0a8c75c63e1.png)

Mobile Horizontal View
![sc20140305-205157](https://f.cloud.github.com/assets/6855029/2341444/32be94b0-a4db-11e3-8369-f7cd549f1f1c.png)

Details:
Joomla! Version = 3.2.2
Grid GK5
Chrome Version = 33.0.1750.117 m
PHP = 5.3.27
Contact Mail: ivan@accesoalanube.com

Thank you so much for your valued help!

Ivan

**Comment by dziudek** [comment]
Hello,

Your problem is connected with fact, that your content isn't square and responsive. The Grid G5 module structure is based on the squares, so your content should be square and responsive too.

**Comment by Accesoalanube** [comment]
Thank you so much Dzludek!

Ok I would change my content to a totally square structure, some questions:
1. Which is the recommended image size for a 1x1 block and also for a 2x2 block??
2. How can I make my images to be responsive?? (do I have to use "auto" on width)
3. Maybe could you provide us with an image list sizes for all the blocks...

Thank you very much for this great assistance!

**Comment by dziudek** [comment]
1) In your case it will be 164 x 164px for 1x1 and 328 x 328 for 2 x 2, please remember that it is better to use a little bigger images - it will be looking better on the mobile devices where the blocks are usually bigger 

2) The best way will be adding to the images the following CSS code:

``` html
style="width: 100%; height: 100%; position: absolute; top: 0; left: 0"
```

3) This kind of list doesn't exists, because it depends from the size of 1x1 block, which is different for every website (it depends from the module width). In your case 1 unit is 164px.
