### ISSUE TITLE
Magazin Template

### ISSUE THREAD

**Issue by Robert1402** [GavickPro/Grid-GK5#8]
I cann't update my website Joomla 2.5 with Magazin Template.
How much will be it cost if you do it for me?
www.diamantbericht.de

**Comment by Robert1402** [comment]
I cann't update my website Joomla 2.5 with Magazin Template.
How much will be it cost if you do it for me?
www.diamantbericht.de

**Comment by dziudek** [comment]
Hello,

If you have a custom work request please use our ticket system: https://www.gavick.com/supportdesk/index.php?/Tickets/Submit

**Comment by Robert1402** [comment]
I instaled your template Magazin, but the Button register on the top doesn't  work. Where can I change it?

**Comment by Robert1402** [comment]
![image](https://f.cloud.github.com/assets/6908425/2383385/c9d5bdfa-a8fb-11e3-9e98-8c00f73c444f.png)

The link register doesn't work. Where can I change it?

**Comment by dziudek** [comment]
There is a Magazine Joomla Template repository: https://github.com/GavickPro/Magazine-Free-Joomla-Template - there you can report your problems.
